//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Data.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSurveyDetail
    {
        public int EmpSurveyId { get; set; }
        public Nullable<System.Guid> SurveyId { get; set; }
        public string UserId { get; set; }
        public string EmpSurveyLink { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> SurveySubmitDate { get; set; }
    
        public virtual SurveyMaster SurveyMaster { get; set; }
    }
}
