//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Data.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBankOption
    {
        public int AnswerId { get; set; }
        public Nullable<int> QueId { get; set; }
        public string Answers { get; set; }
        public Nullable<bool> CorrectAnswer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual QuestionBank QuestionBank { get; set; }
    }
}
