//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Data.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int SurveyAnsId { get; set; }
        public Nullable<System.Guid> SurveyId { get; set; }
        public Nullable<int> QueId { get; set; }
        public Nullable<int> Selectedoption { get; set; }
    
        public virtual QuestionBank QuestionBank { get; set; }
        public virtual SurveyMaster SurveyMaster { get; set; }
    }
}
