//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survey.Web.Resources.ModelValidations", typeof(ModelValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string Account_InvalidLoginError {
            get {
                return ResourceManager.GetString("Account_InvalidLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login, please try again..
        /// </summary>
        public static string Account_InvalidLoginMessage {
            get {
                return ResourceManager.GetString("Account_InvalidLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Your username is your University login username (e.g. bloggsj2) and not your email address. If you are still experience problems, please visit the ITS Service Desk in the Library..
        /// </summary>
        public static string Account_InvalidLoginMessage1 {
            get {
                return ResourceManager.GetString("Account_InvalidLoginMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Coventry University username (e.g. bloggsj2) and password and click Login..
        /// </summary>
        public static string Account_login_instruction {
            get {
                return ResourceManager.GetString("Account_login_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page..
        /// </summary>
        public static string Account_UnauthorisedAccess_Description {
            get {
                return ResourceManager.GetString("Account_UnauthorisedAccess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Qualification.
        /// </summary>
        public static string Button_Add_Qualification_Save_Label {
            get {
                return ResourceManager.GetString("Button_Add_Qualification_Save_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Qualification..
        /// </summary>
        public static string Dropdown_Qualification_Label {
            get {
                return ResourceManager.GetString("Dropdown_Qualification_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grade/Result..
        /// </summary>
        public static string Dropdown_Result_Label {
            get {
                return ResourceManager.GetString("Dropdown_Result_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select When Exam Sat..
        /// </summary>
        public static string Dropdown_Sitting_Label {
            get {
                return ResourceManager.GetString("Dropdown_Sitting_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subject..
        /// </summary>
        public static string Dropdown_Subject_Label {
            get {
                return ResourceManager.GetString("Dropdown_Subject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year..
        /// </summary>
        public static string Dropdown_Year_Label {
            get {
                return ResourceManager.GetString("Dropdown_Year_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing..
        /// </summary>
        public static string Exception_Development_Message {
            get {
                return ResourceManager.GetString("Exception_Development_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while executing this request, please contact your administrator..
        /// </summary>
        public static string Exception_Production_Message {
            get {
                return ResourceManager.GetString("Exception_Production_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Header_Update_Qualification_Label {
            get {
                return ResourceManager.GetString("Header_Update_Qualification_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Qualification.
        /// </summary>
        public static string Home_AddQualification_Title {
            get {
                return ResourceManager.GetString("Home_AddQualification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Home_Grid_Column_Delete {
            get {
                return ResourceManager.GetString("Home_Grid_Column_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Home_Grid_Column_Edit {
            get {
                return ResourceManager.GetString("Home_Grid_Column_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Home_Grid_Title_Action {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Home_Grid_Title_Faculty {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Code.
        /// </summary>
        public static string Home_Grid_Title_QualificationCode {
            get {
                return ResourceManager.GetString("Home_Grid_Title_QualificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Title.
        /// </summary>
        public static string Home_Grid_Title_QualificationTitle {
            get {
                return ResourceManager.GetString("Home_Grid_Title_QualificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Home_Grid_Title_Remark {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Received.
        /// </summary>
        public static string Home_Grid_Title_Result {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Exam Sat.
        /// </summary>
        public static string Home_Grid_Title_Sitting {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Sitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Home_Grid_Title_Status {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string Home_Grid_Title_StudentName {
            get {
                return ResourceManager.GetString("Home_Grid_Title_StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student No.
        /// </summary>
        public static string Home_Grid_Title_StudentNo {
            get {
                return ResourceManager.GetString("Home_Grid_Title_StudentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Home_Grid_Title_Subject {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Date.
        /// </summary>
        public static string Home_Grid_Title_SubmittedDate {
            get {
                return ResourceManager.GetString("Home_Grid_Title_SubmittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLine.
        /// </summary>
        public static string Home_Grid_Title_TimeLine {
            get {
                return ResourceManager.GetString("Home_Grid_Title_TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Home_Grid_Title_Year {
            get {
                return ResourceManager.GetString("Home_Grid_Title_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Stage.
        /// </summary>
        public static string Home_Search_Title_CourseStage {
            get {
                return ResourceManager.GetString("Home_Search_Title_CourseStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Home_Search_Title_Mode {
            get {
                return ResourceManager.GetString("Home_Search_Title_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Home_Search_Title_Name {
            get {
                return ResourceManager.GetString("Home_Search_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual. Aim.
        /// </summary>
        public static string Home_Search_Title_QualAim {
            get {
                return ResourceManager.GetString("Home_Search_Title_QualAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification  Code.
        /// </summary>
        public static string Home_Search_Title_QualificationCode {
            get {
                return ResourceManager.GetString("Home_Search_Title_QualificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Below is a list of the qualification that we currently have on our records. &lt;/li&gt;
        ///Unfortunately you cannot add any more qualifications, please log out of the system.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Home_Student_Information_Content {
            get {
                return ResourceManager.GetString("Home_Student_Information_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Home_Student_Information_Header {
            get {
                return ResourceManager.GetString("Home_Student_Information_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;You will see a list of the qualification that we know you have already completed. This information is taken from your admissions records. Please check the list carefully. &lt;/li&gt;
        ///&lt;li&gt;If you have additional UK qualifications that appear on the UCAS Tariff and are not listed below. Please add these using the drop down boxes in the table. You should add all the qualifications that you hold which appear in the list of options even if these are not directly related to the subject you are enrolled on (e. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_UGStudent_Information_Content {
            get {
                return ResourceManager.GetString("Home_UGStudent_Information_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occurred while uploading certificate..
        /// </summary>
        public static string Message_Certificate_Error {
            get {
                return ResourceManager.GetString("Message_Certificate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload certificate..
        /// </summary>
        public static string Message_Certificate_Fail {
            get {
                return ResourceManager.GetString("Message_Certificate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields..
        /// </summary>
        public static string Message_Edit_All_Fields_Required {
            get {
                return ResourceManager.GetString("Message_Edit_All_Fields_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Should be less than or equal to 2MB.
        /// </summary>
        public static string Message_FileUpoad {
            get {
                return ResourceManager.GetString("Message_FileUpoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string Message_Grid_No_Record_Found {
            get {
                return ResourceManager.GetString("Message_Grid_No_Record_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some internal error occurred. Please contact administrator..
        /// </summary>
        public static string Message_Internal_Server_Error {
            get {
                return ResourceManager.GetString("Message_Internal_Server_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding qualification..
        /// </summary>
        public static string Message_Qualification_Add_Error {
            get {
                return ResourceManager.GetString("Message_Qualification_Add_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in adding qualification..
        /// </summary>
        public static string Message_Qualification_Add_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Add_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New qualification added and you can find it on &lt;a href=&apos;#&apos; onClick =&quot; $(&apos;#qualificationTab a:eq(1)&apos;).tab(&apos;show&apos;); hideMessage();&quot; =&gt;Pending&lt;/a&gt; qualification tab..
        /// </summary>
        public static string Message_Qualification_Add_Success {
            get {
                return ResourceManager.GetString("Message_Qualification_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect input values..
        /// </summary>
        public static string Message_Qualification_Add_Validation {
            get {
                return ResourceManager.GetString("Message_Qualification_Add_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This qualification is already added..
        /// </summary>
        public static string Message_Qualification_Already_Exists {
            get {
                return ResourceManager.GetString("Message_Qualification_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while approving qualifiaction..
        /// </summary>
        public static string Message_Qualification_Apporve_Error {
            get {
                return ResourceManager.GetString("Message_Qualification_Apporve_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifiaction could not be  approved..
        /// </summary>
        public static string Message_Qualification_Apporve_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Apporve_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification approved successfully..
        /// </summary>
        public static string Message_Qualification_Apporve_Success {
            get {
                return ResourceManager.GetString("Message_Qualification_Apporve_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this qualification?.
        /// </summary>
        public static string Message_Qualification_Delete_Confirm {
            get {
                return ResourceManager.GetString("Message_Qualification_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting qualification..
        /// </summary>
        public static string Message_Qualification_Delete_Error {
            get {
                return ResourceManager.GetString("Message_Qualification_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete qualification..
        /// </summary>
        public static string Message_Qualification_Delete_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification deleted successfully..
        /// </summary>
        public static string Message_Qualification_Delete_Success {
            get {
                return ResourceManager.GetString("Message_Qualification_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating qualification..
        /// </summary>
        public static string Message_Qualification_Edit_Error {
            get {
                return ResourceManager.GetString("Message_Qualification_Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification could not be updated..
        /// </summary>
        public static string Message_Qualification_Edit_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification updated  successfully..
        /// </summary>
        public static string Message_Qualification_Edit_Success {
            get {
                return ResourceManager.GetString("Message_Qualification_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while rejecting qualification..
        /// </summary>
        public static string Message_Qualification_Reject_Error {
            get {
                return ResourceManager.GetString("Message_Qualification_Reject_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifiaction could not be  rejected..
        /// </summary>
        public static string Message_Qualification_Reject_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Reject_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark is required and should not exceed 4000 character..
        /// </summary>
        public static string Message_Qualification_Reject_Remark_Len {
            get {
                return ResourceManager.GetString("Message_Qualification_Reject_Remark_Len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification rejected successfully..
        /// </summary>
        public static string Message_Qualification_Reject_Success {
            get {
                return ResourceManager.GetString("Message_Qualification_Reject_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not able to search..
        /// </summary>
        public static string Message_Qualification_Search_Fail {
            get {
                return ResourceManager.GetString("Message_Qualification_Search_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string PlannerStaff_Search_FacultyCode {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_FacultyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Code.
        /// </summary>
        public static string PlannerStaff_Search_QualificationCode {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_QualificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PlannerStaff_Search_Status {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student No.
        /// </summary>
        public static string PlannerStaff_Search_StudentId {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string PlannerStaff_Search_SubmittedDate {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_SubmittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string PlannerStaff_Search_SubmittedFromDate {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_SubmittedFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string PlannerStaff_Search_SubmittedToDate {
            get {
                return ResourceManager.GetString("PlannerStaff_Search_SubmittedToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Qualification.
        /// </summary>
        public static string Student_Existing_Qual_Label {
            get {
                return ResourceManager.GetString("Student_Existing_Qual_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Qualification(s).
        /// </summary>
        public static string Student_ExistingQual_Header {
            get {
                return ResourceManager.GetString("Student_ExistingQual_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Student_Grid_Column_Approve {
            get {
                return ResourceManager.GetString("Student_Grid_Column_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Student_Grid_Column_Edit {
            get {
                return ResourceManager.GetString("Student_Grid_Column_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Student_Grid_Column_Reject {
            get {
                return ResourceManager.GetString("Student_Grid_Column_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Qualification.
        /// </summary>
        public static string Student_Pending_Qual_Label {
            get {
                return ResourceManager.GetString("Student_Pending_Qual_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Qualification(s).
        /// </summary>
        public static string Student_PendingQual_Header {
            get {
                return ResourceManager.GetString("Student_PendingQual_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Qualification.
        /// </summary>
        public static string Student_Rejected_Qual_Label {
            get {
                return ResourceManager.GetString("Student_Rejected_Qual_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Qualification(s).
        /// </summary>
        public static string Student_RejectedQual_Header {
            get {
                return ResourceManager.GetString("Student_RejectedQual_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file extensions:.
        /// </summary>
        public static string Validation_Certificate_Extenstions {
            get {
                return ResourceManager.GetString("Validation_Certificate_Extenstions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size can&apos;t exceed.
        /// </summary>
        public static string Validation_Certificate_MaxSize {
            get {
                return ResourceManager.GetString("Validation_Certificate_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is too small.
        /// </summary>
        public static string Validation_Certificate_MinSize {
            get {
                return ResourceManager.GetString("Validation_Certificate_MinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File&apos;s length is zero, or no files found..
        /// </summary>
        public static string Validation_Certificate_Required {
            get {
                return ResourceManager.GetString("Validation_Certificate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date should be less than To Date..
        /// </summary>
        public static string Validation_Date_Range_Invalid {
            get {
                return ResourceManager.GetString("Validation_Date_Range_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select both dates..
        /// </summary>
        public static string Validation_Dates_Required {
            get {
                return ResourceManager.GetString("Validation_Dates_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Qualification..
        /// </summary>
        public static string Validation_Qualification_Required {
            get {
                return ResourceManager.GetString("Validation_Qualification_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length for comment is 400 characters..
        /// </summary>
        public static string Validation_Remark_Length {
            get {
                return ResourceManager.GetString("Validation_Remark_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grade/Result..
        /// </summary>
        public static string Validation_Result_Required {
            get {
                return ResourceManager.GetString("Validation_Result_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select When Exam Sat..
        /// </summary>
        public static string Validation_Sitting_Required {
            get {
                return ResourceManager.GetString("Validation_Sitting_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subject..
        /// </summary>
        public static string Validation_Subject_Required {
            get {
                return ResourceManager.GetString("Validation_Subject_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year..
        /// </summary>
        public static string Validation_Year_Required {
            get {
                return ResourceManager.GetString("Validation_Year_Required", resourceCulture);
            }
        }
    }
}
